base_url = "https://sahilgautam.in"
title = "Sahil Gautam"
description = "This is an example description"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "light"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content"

menu = [
    { name = "libreoffice-hacking", url = "/libreoffice", weight = 1 },
    { name = "blogs", url = "/blogs", weight = 1 },
    { name = "#tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "github", url = "https://github.com/printfdebugging/", icon = "github" },
    { name = "linkedin", url = "https://linkedin.com/in/printfdebugging/", icon = "linkedin" },
    { name = "email", url = "mailto:sahil@libreoffice.org", icon = "email" },
    { name = "youtube", url = "https://youtube.com/@printfdebugging", icon = "youtube" },
    { name = "rss", url = "/atom.xml", icon = "rss" },
]

custom_css = []

[extra.analytics]
enabled = false

# [extra.analytics.goatcounter]
# user = "your_user"
# host = "example.com" # default= goatcounter.com

# [extra.analytics.umami]
# website_id = "43929cd1-1e83...."
# host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is

